# .github/workflows/deploy-dev.yml
name: Deploy Cryptofox Corp Web (Dev) - Frontend & API

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # This sets Node for the GitHub Actions runner itself
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      # === Client (Frontend) Build Steps ===
      - name: Clean npm cache (Client - Aggressive)
        run: npm cache clean --force
        working-directory: ./client

      - name: Remove client node_modules and package-lock.json (Aggressive)
        run: |
          rm -rf node_modules
          rm package-lock.json
        working-directory: ./client

      - name: Install Frontend Dependencies (Reverted to npm install)
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Force AJV-keywords compatible version
        working-directory: ./client
        run: npm install ajv-keywords@^3.5.2 --legacy-peer-deps

      - name: Build Frontend (React)
        working-directory: ./client
        run: npm run build
        env:
          CI: false

      # === Server (API) Build Steps ===
      # Note: We're removing the explicit npm install steps here,
      # as Oryx will perform its own installation and build based on api_location.
      # The previous manual installs caused issues or were redundant.

      - name: Deploy Frontend & API to Azure Static Web Apps
        id: swa_deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'client/build'
          api_location: 'server'
          output_location: ''
          skip_app_build: true # We pre-built the client
          skip_api_build: false
          # --- NEW CRITICAL CHANGE: Explicitly pass NODE_VERSION to Oryx ---
          api_build_properties: "NODE_VERSION=~20" # This instructs Oryx to use Node.js 20
                                                    # The "~" means compatible with 20.x
          # Alternatively, you could try setting a specific version like "NODE_VERSION=20.x" or "NODE_VERSION=20.19.3"
                                                    # if "~20" doesn't work.
                                                    # For Node.js functions, Oryx often auto-detects from package.json
                                                    # but explicitly setting it here should override any misdetection.


      - name: Output Deployment Details
        run: |
          echo "Frontend URL: ${{ steps.swa_deploy.outputs.static_web_app_url }}"