# GitHub Actions Workflow for Cryptofox Corp Web Deployment
# This workflow deploys the React frontend to Azure Static Web Apps
# and the Node.js backend API to the integrated App Service.

name: Deploy Cryptofox Corp Web (Dev)

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use a Linux runner for the build and deploy steps
    environment: dev # Associate this job with the 'dev' environment (optional, for GitHub Environments)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Checkout the source code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Use Node.js 18.x as specified in your Bicep
        with:
          node-version: '18.x' # Ensure this matches your Node.js backend version
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install Frontend Dependencies
        working-directory: ./client # Navigate to the client directory
        run: npm install # Install npm packages for the React frontend

      - name: Build Frontend (React)
        working-directory: ./client # Navigate to the client directory
        run: npm run build # Run the build script defined in client/package.json
        env:
          CI: false # Suppress warnings treated as errors in CI environments

      - name: Install Backend Dependencies
        working-directory: ./server # Navigate to the server directory
        run: npm install # Install npm packages for the Node.js backend

      - name: Deploy to Azure Static Web Apps
        id: swa_deploy
        uses: azure/static-web-apps-deploy@v1 # Use the Azure Static Web Apps Deploy action
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'client/build' # Points to the built frontend artifacts
          api_location: '/server' # Path to your Node.js API code
          output_location: '' # Empty, as app_location is already the output
          skip_app_build: true
          skip_api_build: true
          # Explicitly set the API runtime for Azure Functions
          api_language: 'nodejs' # Specifies the language for the API
          api_runtime: 'node:18' # Specifies the Node.js version for the API runtime
          # Remove api_build_command if `npm install` is sufficient and no other build step is needed
          # If your API has a specific build step (e.g., TypeScript compilation), add it here.
          # For a simple Node.js API, `npm install` is often enough, which is done in a prior step.
          # If you need a specific build script, it would be:
          # api_build_command: 'npm run build-api' # (assuming you have this script in server/package.json)
          
      - name: Output Deployment Details
        run: |
          echo "Frontend URL: ${{ steps.swa_deploy.outputs.static_web_app_url }}"
          echo "Backend URL: ${{ steps.swa_deploy.outputs.api_url }}"
