# .github/workflows/deploy-dev.yml
name: Deploy Cryptofox Corp Web (Dev) - Frontend & API

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # This sets Node for the GitHub Actions runner itself
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      # === Server (API) Pre-Build Steps for Shared Resources ===
      # IMPORTANT: Moved 'Copy Blog Posts to API Folder' here to run BEFORE client build
      # This ensures 'server/posts' exists BEFORE client build (which includes sitemap generation)
      - name: Copy Blog Posts to API Folder
        run: cp -R posts ./server/posts # This copies 'posts' from repo root to 'server/posts'
                                       # So it gets included when 'server' is deployed as API AND available for client sitemap generation

      # Add these lines for a super clean API install during deployment
      - name: Clean npm cache (API - Aggressive)
        run: npm cache clean --force
        working-directory: ./server

      - name: Remove API node_modules and package-lock.json (Aggressive)
        run: |
          rm -rf node_modules
          rm package-lock.json || true # '|| true' to prevent error if no lock file
        working-directory: ./server
      # End of aggressive clean for API

      # === Client (Frontend) Build Steps ===
      - name: Clean npm cache (Client - Aggressive)
        run: npm cache clean --force
        working-directory: ./client

      - name: Remove client node_modules and package-lock.json (Aggressive)
        run: |
          rm -rf node_modules
          rm package-lock.json
        working-directory: ./client

      - name: Install Frontend Dependencies (Reverted to npm install)
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Force AJV-keywords compatible version
        working-directory: ./client
        run: npm install ajv-keywords@^3.5.2 --legacy-peer-deps

      - name: Build Frontend (React)
        working-directory: ./client
        run: npm run build
        env:
          CI: false

      - name: Deploy Frontend & API to Azure Static Web Apps
        id: swa_deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'client/build'
          api_location: 'server' # This targets the managed function app backend
          output_location: ''
          skip_app_build: true # We pre-built the client
          skip_api_build: false
          # The api_build_properties line is removed as it's not needed for the managed backend and caused warnings.

      - name: Output Deployment Details
        run: |
          echo "Frontend URL: ${{ steps.swa_deploy.outputs.static_web_app_url }}"