# GitHub Actions Workflow for Cryptofox Corp Web Deployment
# This workflow deploys the React frontend to Azure Static Web Apps
# and the Node.js backend API to the integrated App Service.

name: Deploy Cryptofox Corp Web (Dev)

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use a Linux runner for the build and deploy steps
    environment: dev # Associate this job with the 'dev' environment (optional, for GitHub Environments)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Checkout the source code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Use Node.js 18.x as specified in your Bicep
        with:
          node-version: '18.x' # Ensure this matches your Node.js backend version
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install Frontend Dependencies
        working-directory: ./client # Navigate to the client directory
        run: npm install # Install npm packages for the React frontend

      - name: Build Frontend (React)
        working-directory: ./client # Navigate to the client directory
        run: npm run build # Run the build script defined in client/package.json
        env:
          CI: false # Suppress warnings treated as errors in CI environments

      - name: Install Backend Dependencies
        working-directory: ./server # Navigate to the server directory
        run: npm install # Install npm packages for the Node.js backend

      - name: Deploy to Azure Static Web Apps
        id: swa_deploy
        uses: azure/static-web-apps-deploy@v1 # Use the Azure Static Web Apps Deploy action
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'client/build' # Points to the built frontend artifacts
          api_location: '/server' # Path to your Node.js API code
          output_location: '' # Empty, as app_location is already the output
          skip_app_build: true
          skip_api_build: true
          # Alternative way to specify API runtime, explicitly using 'api_build_command'
          # and setting the language via an environment variable that Oryx might pick up.
          # We'll also try a direct 'app_settings' approach if this doesn't work.
          api_build_command: 'npm install && npm run build-api' # You might need to define 'build-api' in server/package.json if it doesn't exist
          # This is the key part for the language info.
          # The SWA deploy action often relies on the 'platform' section in staticwebapp.config.json
          # or environment variables that Oryx (the build engine) can detect.
          # Let's try setting an environment variable directly for the action.
          # This is less common but might force the detection.
          # Also, ensuring the Node.js version is explicitly set for the API.
          # Note: api_language and api_runtime are standard, but if they're not working,
          # this indicates a deeper issue or a need for a different approach.
          # We will remove api_language and api_runtime to avoid potential conflicts
          # and rely on the build command and app_settings if needed.
          # For now, let's try to ensure the build command itself sets the context.

          # Let's try passing the runtime version directly in the `app_settings` for the API.
          # This is typically for environment variables, but sometimes helps with runtime detection.
          # This is a less common workaround for this specific error.
          # The primary fix should be `api_language` and `api_runtime`, but since that failed,
          # we're exploring alternatives.
          app_settings: |
            FUNCTIONS_WORKER_RUNTIME=node
            NODE_VERSION=~18 # Use the same major version as setup-node

      - name: Output Deployment Details
        run: |
          echo "Frontend URL: ${{ steps.swa_deploy.outputs.static_web_app_url }}"
          echo "Backend URL: ${{ steps.swa_deploy.outputs.api_url }}"
