jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps # Added --legacy-peer-deps

      - name: Build Frontend (React)
        working-directory: ./client
        run: npm run build
        env:
          CI: false

      - name: Deploy Frontend to Azure Static Web Apps
        id: swa_deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'client/build'
          api_location: ''
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Output Deployment Details
        run: |
          echo "Frontend URL: ${{ steps.swa_deploy.outputs.static_web_app_url }}"