# .github/workflows/e2eTest.yml
name: E2E and Visual Regression Tests

on:
  push:
    branches:
      - master
      - main
      - develop # Assuming you use a develop branch for features

  pull_request:
    branches:
      - master
      - main
      - develop

# Add workflow run retention policy here
# This will keep workflow runs and their associated artifacts for 14 days.
# Adjust this value (e.g., 7, 30, 60) based on your team's needs for history.
retention-days: 14 

jobs:
  test:
    timeout-minutes: 15 # Set a reasonable timeout for the job
    runs-on: ubuntu-latest # GitHub-hosted runner with Ubuntu OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up Node.js environment
        with:
          node-version: '20' # Use the Node.js version you are using locally

      - name: Install root dependencies
        run: npm install # Installs dependencies from your root package.json

      - name: Install client and server dependencies
        run: |
          npm install --prefix client
          npm install --prefix server

      - name: Install Playwright browsers
        run: npx playwright install --with-deps # Installs Chromium, Firefox, WebKit browsers

      - name: Run E2E and Visual Regression Tests (Generate Linux Snapshots)
        # TEMPORARY CHANGE: Now correctly using npx to find start-server-and-test
        # This will start your app and then then run Playwright with --update-snapshots.
        # This step will still report a failure because new snapshots are written.
        # We will revert this after downloading the artifacts.
        run: npx start-server-and-test "npm run start:all" http://localhost:3000 "npx playwright test --update-snapshots"

      - name: Upload Playwright test results (on failure)
        if: failure() # This step only runs if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/ # Path to the Playwright HTML report
          retention-days: 5 # This specific artifact will be kept for 5 days.
                            # Note: The overall workflow run's retention (14 days) also applies.
                            # This 'retention-days' here is specific to this artifact.